OBTENER EL PROMEDIO DE COMPRAS POR PROVEEDOR

SELECT p.DNI, p.NOMBRE, AVG(CANTIDAD) AS PROMEDIO_COMPRAS
FROM PROVEEDORES p
JOIN COMPRAS c ON p.DNI = c.DNI_PROVEEDOR
GROUP BY p.DNI, p.NOMBRE;

OBTENER TOTAL VENTAS Y FACTURACION POR CLIENTE

SELECT c.NOMBRE, COUNT(v.ID_VENTA) AS TOTALVENTAS, SUM(f.TOTALFACTURACION) AS TOTALFACTURACION
FROM CLIENTE c
LEFT JOIN VENTA v ON c.DNI = v.DNI_CLIENTE
LEFT JOIN FACTURACION f ON v.ID_VENTA = f.ID_VENTA
GROUP BY c.NOMBRE;

OBTENER EL PROVEEDOR CON MAYOR NUMERO DE COMPRAS

SELECT p.NOMBRE, COUNT(*) AS TOTAL_COMPRAS
FROM PROVEEDORES p
JOIN COMPRAS c ON p.DNI = c.DNI_PROVEEDOR
GROUP BY p.NOMBRE
HAVING COUNT(*) = (
    SELECT MAX(COMPRAS_COUNT)
    FROM (
        SELECT COUNT(*) AS COMPRAS_COUNT
        FROM COMPRAS
        GROUP BY DNI_PROVEEDOR
    )
);