Dime los telefonos de todo cliente que haya realizado alguna venta

SELECT c.Telefono
FROM CLIENTE c
JOIN VENTA v ON c.DNI = v.DNI_CLIENTE;



Dime que prodcutos vende Proveedor 1

SELECT pr.NOMBRE AS PROVEEDOR, pr.DNI AS DNI_PROVEEDOR, p.ID_PRODUCTO AS PRODUCTO, p.DESCRIPCION
FROM PROVEEDORES pr
JOIN PRODUCTOS p ON pr.DNI = p.DNIPROVEEDOR
WHERE pr.NOMBRE = 'Proveedor 1'
ORDER BY pr.NOMBRE;



OBTENER EL PROVEEDOR CON MAYOR NUMERO DE COMPRAS

SELECT p.NOMBRE, COUNT(*) AS TOTAL_COMPRAS
FROM PROVEEDORES p
JOIN COMPRAS c ON p.DNI = c.DNI_PROVEEDOR
GROUP BY p.NOMBRE
HAVING COUNT(*) = (
    SELECT MAX(COMPRAS_COUNT)
    FROM (
        SELECT COUNT(*) AS COMPRAS_COUNT
        FROM COMPRAS
        GROUP BY DNI_PROVEEDOR
    )
);