DROP TABLE CLIENTE CASCADE CONSTRAINTS;
CREATE TABLE CLIENTE(
	DNI varchar2(9) PRIMARY KEY,
	Nombre varchar2(40),
	Telefono number(9),
	Direccion varchar2 (90)
);

DROP TABLE VENTA CASCADE CONSTRAINTS;
CREATE TABLE VENTA(
	ID_Venta varchar2(30) PRIMARY KEY,
	FechaVenta date,
	DNI_CLIENTE varchar2(9),
	TotalVenta number(15),
	CONSTRAINT FK_VENT_CLI FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
);
DROP TABLE FACTURACION CASCADE CONSTRAINTS;
CREATE TABLE FACTURACION(
	ID_FACTURACION varchar2(30) PRIMARY KEY,
	FechaFacturacion date,
	TotalFacturacion number(15),
	ID_Venta varchar2(30),
	DNICliente varchar2(9),
	CONSTRAINT FK_FACT_CLI FOREIGN KEY (DNICliente) REFERENCES CLIENTE(DNI),
	CONSTRAINT FK_FACT_VENTA FOREIGN KEY(ID_Venta) REFERENCES VENTA(ID_Venta)
);
DROP TABLE PROVEEDORES CASCADE CONSTRAINTS;
CREATE TABLE PROVEEDORES(
	DNI varchar2(9),
	Nombre varchar2(40),
	Telefono number(9),
	Correo varchar2 (90),
	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (DNI)
);
CREATE TABLE PRODUCTOS(
	ID_PRODUCTO varchar2(30) PRIMARY KEY,
	DESCRIPCION varchar2(80),
	CATEGORIA varchar2(20),
	NOMBRE varchar2(40),
	DNIPROVEEDOR varchar2(9),
	CONSTRAINT FK_PROD_PROVEEDOR FOREIGN KEY (DNIPROVEEDOR) REFERENCES PROVEEDORES(DNI)
);
DROP TABLE COMPRAS CASCADE CONSTRAINTS;
CREATE TABLE COMPRAS(
	ID_COMPRA varchar2(30) PRIMARY KEY,
	ID_PRODUCTO varchar2(30),
	DNI_PROVEEDOR varchar2(9),
	CANTIDAD varchar2(5),
	FECHACOMPRA date,
	PRECIO varchar2(8),
	CONSTRAINT FK_COMPRAS_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_COMPRAS_PROVEEDOR FOREIGN KEY (DNI_PROVEEDOR) REFERENCES PROVEEDORES(DNI)
);

CREATE TABLE SUMINISTRA_PROV_COMP_PROD(
    ID_COMPRA VARCHAR2(30),
    ID_PRODUCTO VARCHAR2(30),
    DNI VARCHAR2(9),
    CONSTRAINT PK_SUMINISTRA_PROV_COMP_PROD PRIMARY KEY (ID_COMPRA,ID_PRODUCTO,DNI),
    CONSTRAINT FK_ID_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
    CONSTRAINT FK_ID_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_DNI FOREIGN KEY (DNI) REFERENCES PROVEEDORES(DNI)
);